# Generated by Django 5.2.3 on 2025-06-18 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('service', models.CharField(choices=[('yazılım', 'Yazılım'), ('donanım', 'Donanım'), ('danışmanlık', 'Danışmanlık')], max_length=20, verbose_name='Hizmet')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Formu',
                'verbose_name_plural': 'İletişim Formları',
                'ordering': ['-created_at'],
            },
        ),
    ]
